### ISSUE TITLE
How to use the opportunities and functionality EXT: view without EXT: view?

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/view#26]
Hello, all! 
I have question ... 
I about EXT: view ... OBSOLETE - Feature set now available in TYPO3 core 
How to use the opportunities and functionality EXT: view without EXT: view???

**Comment by typo3ua** [comment]
... sorry
I deleted EXT: view and left TS configuration.
Everything works well.
Thanks.

**Comment by cedricziel** [comment]
Hi @typo3ua ;

There's documentation in the TSRef about that feature (see templateRootPaths, layoutRootPaths and partialRootPaths [note the trailing 's']) http://docs.typo3.org/typo3cms/TyposcriptReference/ContentObjects/Fluidtemplate/Index.html#cobj-fluidtemplate-properties-layoutrootpaths .

## Example:

```
page.10 = FLUIDTEMPLATE
page.10.file = EXT:sitedesign/Resources/Private/Templates/Main.html
page.10.partialRootPaths {
        # Lower priority (=lower number) indizes get searched first
        10 = EXT:sitedesign/Resources/Private/Partials
        # If you have a partial that resides in the exact same (relative) path with the exact
        # same Filename, it will be found there
        20 = EXT:sitemodification/Resources/Private/Partials
}
```
